version: "3.7"
services:
  mysikil:
    container_name: sf-mysql
    image: nimdasx/sf-mysql
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
    networks:
      - sf-net
    environment:
      - MYSQL_ROOT_PASSWORD=q
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    restart: always
networks:
  sf-net:
    name: sf-net
volumes:
  data:
#    external: true