version: "3.7"
services:
  mysikil:
    build: .
    container_name: sf-mysql-container
    image: nimdasx/sf-mysql:latest
    ports:
      - 3306:3306
    volumes:
      - sf-mysql-data:/var/lib/mysql
    networks:
      - sf-net
    environment:
      - MYSQL_ROOT_PASSWORD=q
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    restart: always
networks:
  sf-net:
    name: sf-net
volumes:
  sf-mysql-data:
    external: true